name: Run API Tests with Newman

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      # 1) Гарантируем, что есть папка для отчёта
      - name: Create screenshots directory
        run: mkdir -p screenshots

      # 2) Запускаем коллекцию и НЕ падаем, чтобы отчет гарантированно создался
      - name: Run Postman collection via Newman
        run: |
          newman run postman/saucedemo_collection.json \
            --environment environment.json \
            --reporters cli,html \
            --reporter-html-export screenshots/newman_report_example.html \
            --suppress-exit-code 1

      # 3) Всегда загружаем HTML-отчет, даже если ассерты упали
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: screenshots/newman_report_example.html
